name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v1
    - name: Install pytorch
      run: sudo apt-get update && sudo apt install -y libunwind-dev && sudo apt-get install libtorch-dev
    - name: Meson Build
      uses: BSFishy/meson-build@v1.0.3
      with:
        action: test
        directory: build
        options: --verbose
        meson-version: 0.55.3
      
